### ISSUE TITLE
Initial error

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#1]
![error1](https://cloud.githubusercontent.com/assets/16385845/12684385/77eb040e-c673-11e5-8670-8b0979fa0919.PNG)

I just tried to run ADDICT and came up with an immediate error.  I just selected the cif file, it filled the mol2 file automatically and then I selected the output folder.  I then left everything default and clicked Run.

**Comment by bizzinho** [comment]
Ok, I see. The class datetime must be a new feature of matlab 2014... If possible, I suggest using a newer Matlab version until I have time to write a patch

**Comment by bizzinho** [comment]
Ps. Explanation: datetime is used to find the current time that is written to the log

**Comment by carltilbury** [comment]
Ok.  I ran it on 2014a but will update to the new version of matlab.

**Comment by bizzinho** [comment]
Ok, let me know. I tested it on 2014b and simply assumed a was the same. I can write around it, but won't get to it before Monday. Worst case you can comment out all instances of datetime, they are not essential (all just writing to the log file)

**Comment by bizzinho** [comment]
Can you try whether this works in Matlab 2013?

x = clock;
[num2str(x(3)),'-',num2str(x(2),'%02.0f'),'-',num2str(x(1)),' ',num2str(x(4)),':',num2str(x(5)),':',num2str(x(6),'%2.0f')]

We can change the date format to the american one as well, even though the order month/day/year is of course ungodly against all laws of nature.

**Comment by bizzinho** [comment]
Probem is patched, replaced datestr(datetime) with custom string creation from clock.
