### ISSUE TITLE
ADDICT encountered an error when runing the solvent sweep for paracetamol

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#11]
Hello Dave,
ADDICT encountered an error when I runing the solvent sweep for paracetamol.
![1](https://cloud.githubusercontent.com/assets/17035064/12929459/a7f25f28-cf27-11e5-9bf6-ad3d2f06e77b.png)
![2](https://cloud.githubusercontent.com/assets/17035064/12929464/ae7b7a96-cf27-11e5-8901-8aa8232c7634.jpg)

**Comment by bizzinho** [comment]
My guess is that the ratio between L4 and L3 becomes very large (probably 100). ADDICT then wants to set the slider to the corrsponding value but can't because I have limited the range from exp(-3) to exp(3). I have to think for a second how I want to deal with this.

**Comment by bizzinho** [comment]
OK, the slider will respect the [-3,3] bounds and will be projected if the value lies outside of that range. Hopefully this should result in minimal confusion as the morphology domain at aspect ratio 20 should be close to that of 100. Let's see.

You can now also click on the various points and will be given information regarding the solvent in the status bar on the left. Furthermore, I have implemented markers that vary depending on whether a point lies within the same slice of the morphology map that is currently shown or not (^ if in a lower slice, v if in a higher slice, o if in the same slice)
