### ISSUE TITLE
Error with adipac14 CIF file

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#12]
I'm attempting to run addict with an optimzed CIF file for adipac14 and get the following error:

![new error 1](https://cloud.githubusercontent.com/assets/16385845/12969985/5af9bb6e-d03d-11e5-98ae-18cefb3de95e.PNG)
![new error 2](https://cloud.githubusercontent.com/assets/16385845/12969987/5afacfc2-d03d-11e5-9d57-4b29e549b70e.PNG)
![new error 3](https://cloud.githubusercontent.com/assets/16385845/12969986/5afad90e-d03d-11e5-987b-1ce745156665.PNG)

I tried running without the morphology map or lattice plot, with the solvent sweep and vapor growth, but always get some form of the same error.  I'll email you the CIF file and mol2 file I'm using to test your end.

**Comment by carltilbury** [comment]
The mol2 file in this case has atom codes manually written in by me instead of the usual column of 1's after the 'c3' designations.  But I fixed this and the error appears to persist.

**Comment by bizzinho** [comment]
The problem appears to be that ADDICT is unable to reconstruct more than two facets. I have tested the cif file you provide with the old version (1.8) and it failed as well. Have you tested it with the old ADDICT? If it worked for you, your and my version of old-ADDICT must differ somehow. In that case, can you send me your version so I can try to figure out where things go wrong?

Thx

**Comment by carltilbury** [comment]
![new error 4](https://cloud.githubusercontent.com/assets/16385845/13060411/1c0e9bfc-d3e6-11e5-8ac0-e0d56f895394.PNG)

I tested version 1.7 of ADDICT and get an error also with the optimized adipic acid cif file.  I'm pretty sure Jinjijn has tested ADDICT successfully with the optimized CIF file so I'll try and get it off her to see what might be playing up.

**Comment by carltilbury** [comment]
The optimized cif file from Jinjin for ADIPAC works ok so I've closed this
