### ISSUE TITLE
Solvent sweep error

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#13]
When I run the solvent sweep, I'm struggling to cycle through the shape predictions for all solvents.  The log shows every case being completed, but upon cycling through the shapes do not update.  I tried turning off the morphology map, which didn't help.

Additionally, loading the figures for shapes in each solvent (saved in the output folder) often fails to load the crystal shape image and instead loads an image of the input panel running.

Not sure what to upload for proof - let me know if you can't replicate and what you want!

**Comment by carltilbury** [comment]
Cancel the latter part of this - I realized that the figs are active input panels so I can switch to the shape.

**Comment by bizzinho** [comment]
Can you tell me for which compound you ran into problems? I will try it with Naphtalene now while I go for lunch.

**Comment by bizzinho** [comment]
I had no problems with Naphtalene, cycles through different shapes and plots are updated... maybe once you let me know which compound was affected I'm able to reproduce it!

**Comment by carltilbury** [comment]
![cycling error 1](https://cloud.githubusercontent.com/assets/16385845/13060694/1d3f10fe-d3e8-11e5-9edf-7f15f319dd74.PNG)
![cycling error 2](https://cloud.githubusercontent.com/assets/16385845/13060695/1d3f2f8a-d3e8-11e5-95f8-64afc4dcd0c5.PNG)
![cycling error 3](https://cloud.githubusercontent.com/assets/16385845/13060697/1d42b65a-d3e8-11e5-81bd-e6f5ee70ffa4.PNG)
![cycling error 4](https://cloud.githubusercontent.com/assets/16385845/13060696/1d3f8a52-d3e8-11e5-964c-c1d88cfa2e3d.PNG)

I tested for naphthalene also - the aspect ratio plots appear to show different calculated values, yet the crystal shape remains identical (I've shown 3 above as an example, alongside the log output that  shows relative face areas should be changing).

**Comment by carltilbury** [comment]
Tested it again with Plot Lattice and Calculate morphology map selected (before I was deselecting them) and things worked:
![cycling error 5](https://cloud.githubusercontent.com/assets/16385845/13061007/17a2ff50-d3ea-11e5-9f86-9a1476b09d24.PNG)

Additionally, as you can see from the above image, sometimes the solvent is incorrectly displayed on the legend alongside T and S, might be worth changing it to:

NAPHTA10 in
Methyl Ethyl Ketone
T = 298 K
S = 1.04

Deselecting just plot lattice returns the following error, though the program still runs afterwards and I didn't have any cycling errors like the earlier post.
![deselect plot lattice](https://cloud.githubusercontent.com/assets/16385845/13061142/d2dd2250-d3ea-11e5-9a62-314da61e95d0.PNG)

Deselecting just 'calculate morphology map' appears to run fine but the shapes displayed are all the same upon cycling.

**Comment by bizzinho** [comment]
OK, interesting.

- solvent name suggestion will be implemented.
- analyze behavior with plot lattice off
- analyze results with calculate morph map off

I will send you an updated ADDICT version as soon as I'm done with the above points.

**Comment by bizzinho** [comment]
All issues should be fixed now
