### ISSUE TITLE
Should ADDICT cycle to the coordinates of a point when clicking on it?

### ISSUE THREAD

**Issue by bizzinho** [bizzinho/ADDICT_Issues#18]
Currently, the status bar simply tells you on what point (name and solvent) you clicked. Would you like ADDICT to cycle to this shape directly?

**Comment by carltilbury** [comment]
Not sure, can you elaborate?

**Comment by bizzinho** [comment]
Sure.

Right now, when you click on a morphology marker within the morphology map, the status bar on the l.h.s. will show: "You hust clicked on XXX in YYY (solvent)".

Instead of just indicating this in the status bar, I could make it so that the default behavior is to jump to this morphology, i.e., do the equivalent of cycling until you reach this point (update all plots, etc.)

**Comment by carltilbury** [comment]
Got it.  I think that would be a good feature.

**Comment by bizzinho** [comment]
Done
