### ISSUE TITLE
Lovastatin fail

### ISSUE THREAD

**Issue by bizzinho** [bizzinho/ADDICT_Issues#22]
When I run the solvent sweep for lovastatin, there is no any point shown in the morphology map. And the "Start PBC viewer" still does not work.

**Comment by bizzinho** [comment]
The problem arises because for all solvent, the third-fastest growing facet has a relative growth rate = 100, which lies outside of the morphology domain. I see the following options:

- Increase the axes limits in order to include the point 100 (ln(100) \approx 4.6); I'm not a big fan of this because the maps are already pixelated
- Reduce the default maximum relative growth rate to something smaller than 100
- Ignore facet families with R = 100 for morphology map calculation

Please let me know what you prefer

**Comment by carltilbury** [comment]
Option 3 might not work - for Lovastatin each facet except {210} has R=100, so we couldn't calculate the map if we ignored those.

For option 2 - selecting R=20 instead would still lead to most such faces growing out of the morphology where appropriate, and would fit on the current dimensions of the map.  This is probably the move, however, I don't know what conditions lead ADDICT to pick R=100, but I would assume it has something to do with expecting rough growth on those facets.

Jinjin - can you explore and work out in what cases R becomes 100?  The shape predicted of course depends on it, and picking an arbitrary value is obviously simplistic - it would be useful to have a warning indicating that the shape prediction is now qualitative only.

**Comment by bizzinho** [comment]
There is a way of tackling the issue for option 3, namely by simply copying L2 into L3, the result is a morphology map with the diagonal as mirror axis, I have tried it and this works.

Because I stumbled upon this in the code I'm pretty sure the condition amounts to
``` if R>100
R = 100;
end```
with an implicit assumption that you have rough growth for these cases. I can find the exact location of this code snippet in the old and new version if you like.

Note that also mixed solutions are possible, e.g., we could increase the axis limits by a not so big amount (say, to 4), and set the upper bound for R to 50 (exp(4) \approx 55)

**Comment by carltilbury** [comment]
The main point of truncating it is to get an easily rendered shape then I guess, so picking R=100 makes it look needle like, which may be the prediction, without making it difficult to perceive.  R=20 still looks rod-like (playing around for adipic acid), but R=50 looks OK so maybe that's the move.  I would like ADDICT to display a warning by the shape/R values if possible, indicating that the aspect ratio may be larger but R was truncated at 50 for rendering purposes.

**Comment by bizzinho** [comment]
We can do that, but in order for this to work properly, I think there should be a check whether the facet is present or not (for many cases, R = 100 just results in a virtual facet). Shall we proceed like so?

I set the maximum to 50, increase the axis limits to -4 to 4 and add a warning for cases where R = Rmax  and the facet is still present?

**Comment by carltilbury** [comment]
Yeah that sounds good.

**Comment by bizzinho** [comment]
OK, I've implemented the following behavior:

If R>50, set it to 50. Facets that have either R=50 and/or are not present in the steady state shape get an asterisk added to their legend entry, which notifies the user that he should look at the tooltip. The tooltip then explains what is going on, i.e., it tells the user that rough growth is to be expected and/or the facet is absent in the steady state shape, etc.
