### ISSUE TITLE
Export Figures

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#23]
(1) There are two groups of molecules shown in the export figure, which should have one.
![1](https://cloud.githubusercontent.com/assets/17035064/13479222/49cc64ba-e08a-11e5-9193-694c1bba2e89.jpg)

**Comment by bizzinho** [comment]
The desired behavior was to have both the atom and the molecule view in the two subplots, but there was a typo. I've corrected the error and added subtitles to make it more clear.
