### ISSUE TITLE
Suggestion from Mike

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#27]
Hello Dave,

There are some suggestions from Mike, See the detailed information in the following figure.
Please let me know if you have any comment.
Thank you.

(1) Because the needle shape prediction (such as Lovastatin) will lie outside of the morphology domain, Mike suggested to use "log10" instead of "ln" in the x-coordinate and y-coordinate of morphology map.

(2) Should the "Very ratio L4/L3" be replaced by "L4/L1" in the morphology map? Because the x-coordinate is L3/L1, and y-coordinate is L2/L1. We should use the same reference for L2, L3 and L4.

(3) Put a scale above the slider of fourth facet (Very ratio L4/L3). 

(4) Put "\Detla H_sub.^exp.=" on the top right of Lattice energy figure. If the user doesn't input this value, show \Detla H_sub.^exp.=unknown.

![wp_20160306_009](https://cloud.githubusercontent.com/assets/17035064/13561748/9c18e76c-e3e5-11e5-907b-13291a5e4131.jpg)

**Comment by bizzinho** [comment]
Hejhej

1. We have already adapted this (cf #22 ). I prefer that solution over the log10, but please see yourself and let me know.

2. No, L4/L3 is correct in that it is what can be modified by the slider (note that in versions 2014 and higher, the 4 and 3 are replaced by the actual facet miller indices.. unfortunately, Matlab 2013 doesn't let me do this...). We've had a short discussion about using the case of Napthalene and decided for this ratio.

3. Ok, will do.

4. Ok, will do.

I'll send you the latest version by today evening (Zurich time)

**Comment by bizzinho** [comment]
4. is done

**Comment by bizzinho** [comment]
(3) is done as well. I'm not a big fan of the way I had to implement it, but I see no other option than to use textpanels...

I send you the latest files and close this issue. If (1) and (2) are not ok for any reason we can reopen this discussion.

**Comment by Jinjin-Li** [comment]
Hello Dave, 
For (1), Mike still prefer to use  "log10" instead of "ln" in the x-coordinate and y-coordinate of morphology map, because the change you made still make the point of Lavastatin lies in the most top right corner of morphology map, which is hidden by the sign of "warning". 

Can you try these two ways and compare them. We can pick a better one.

Thanks
Jinjin

**Comment by bizzinho** [comment]
Absolutely, will implement these changes and send you the other version probably this weekend
