### ISSUE TITLE
COM file

### ISSUE THREAD

**Issue by bizzinho** [bizzinho/ADDICT_Issues#33]
The new interface of ADDICT version 2 has missed a function, which is the generation of *.com file. 
This intermediate file is generated by the *.cif, and can be used as another input file to generate the partial charge file using Gaussian calculation.
Taking paracetamol as an example, I show the function of this file in attachment. 
(1) Could you add this function to the new interface of ADDICT?

**Comment by Jinjin-Li** [comment]
Dave, you are right. The only function of 'com' file is to generate the 'mol2' file. ADDICT doesn't load this file again after having the mol2 file. Creating a new button to save it will be best. Also, please put a note on this button, which may showing: the com file will be generated by clicking this button, which is an input for partial charge file generating.

**Comment by bizzinho** [comment]
Just a question for my understanding:

So the mol2 files can be generated from the com file using some separate software?

**Comment by Jinjin-Li** [comment]
Yes, the mol2 files can be generated from the com file using another separate software.

**Comment by bizzinho** [comment]
com file can now be created by providing only cif and output path. user is notified of this possibility through feedback bar
