### ISSUE TITLE
Interface size

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#36]
If I use my desktop computer which has a 22-inch screen, the interface of ADDICT is good. But, If I use a computer with a smaller screen, such as 18-inch. The interface cannot show completely and cannot be dragged even I change the screen resolution. The following are my screen shots when opening ADDICT with different screen resolutions.
If my screen resolution is 1366*768 (the highest), the interface is:
![1](https://cloud.githubusercontent.com/assets/17035064/14831020/a6211dde-0ba8-11e6-89ba-dc7d17fcecf1.png)

If my screen resolution is 1024*768 (the lowest), the interface is:
![2](https://cloud.githubusercontent.com/assets/17035064/14831029/ad856d96-0ba8-11e6-8d35-59962570a8de.png)

**Comment by bizzinho** [comment]
Okay, ADDICT currently has the following window size in pixels: 1100 x 825, which indeed means that it can't be displayed correctly on an 1024vs768 px monitor. The start position (bottom left corner) on screen is (200,200). I could reduce that to make sure the top doesn't get cut off (you can do that, too, by changing the "[200 200 ..." to "[50 50 ..." on line 92 of ADDICT.m

Possible solutions:
1. ~~Make the window resizable~~ -> this is much harder than it sounds and I can't do it
2. Decrease the height and width of the plot windows which are the main reason for the size <-> squeeze the rest of the inputs
3. Leave it as it is and make 1024 upwards a minimum requirement.
4. Rearrange stuff somehow (how???)

Personally, I feel like reducing the size of the window by much would be a mistake, because then you will run into problems with new monitors (everything will look tiny). Trends are clearly toward having larger, higher-res monitors.

Please let me know what course of action you have decided.

**Comment by Jinjin-Li** [comment]
Hi Dave,
Thanks for your reply. 
I changed the number of "[200 200 ..." to "[20 20 ..." on line 92 of ADDICT.m, but the top interface still get cut off (see the top left part)

![1](https://cloud.githubusercontent.com/assets/17035064/14868591/38acb43a-0c83-11e6-84e2-a703df05723e.png)

**Comment by Jinjin-Li** [comment]
Mike said put the minimum resolution requirement for ADDICT on the release notes. I will send you the update version of ADDICT Release Notes which was revised by Mike based on your readme. Could you please give a final read and give some comments?

**Comment by bizzinho** [comment]
Can you send me the revised readme?

**Comment by bizzinho** [comment]
- I have implemented your changes into the .txt file (it is customary to use a file format that can be used on any platform). I have shortened one or two points (the release notes are not supposed to be a help file / documentation)

- The copyright notice should be accompanied by a year. Can you give me the info for Seung Ha?

- I lifted the minimum display resolution to 1280x1024 [(this is not so bad)](http://www.w3schools.com/browsers/browsers_display.asp)

> The ordering of the faces and the coloring of the faces on the Miller indices bar never changes and are always for the vapor grown shape. But above the bar, you can get the new information for the particular solvent that you are using to calculate.

- This has been discussed, yes... but I never realized that I should implement this? This is not how the code runs right now... Please create an issue if you want me to incorporate this.

- I suggest to give the revised version the designation 2.1 to make clear that there have been changes. Is that okay?

**Comment by Jinjin-Li** [comment]
Dave,
-It's Ok to use a file format.
-We don't have any formation for Seung Ha currently.
-It's good to use resolution of 1280*1024.
-If not, how the code runs now?
-Mike wants to put all the changes together in Release Notes including version 2 and version 2.1.

Thanks

**Comment by bizzinho** [comment]
> - It's Ok to use a file format
> -We don't have any formation for Seung Ha currently

Sorry I don't understand...?

> -If not, how the code runs now?
As it always has: the order depends solely on the first op. Condition

> -Mike wants to put all the changes together in Release Notes including version 2 and version 2.1
Okay!

**Comment by bizzinho** [comment]
PS. I will combine all release notes into one, but I maintain that it would be better to call the latest version either 2.1 or 2.0.1 to not have two different 2.0 versions floating around. Do you agree with this?

**Comment by Jinjin-Li** [comment]
Dave,

I agree with you.
How about you send me the update Release notes, I will show it to Mike. If he is fine, we good with it.
Thank you.




 
From: David Ochsenbein
Date: 2016-05-09 10:12
To: bizzinho/ADDICT_Issues
CC: Jinjin-Li; Author
Subject: Re: [bizzinho/ADDICT_Issues] Interface size (#36)
PS. I will combine all release notes into one, but I maintain that it would be better to call the latest version either 2.1 or 2.0.1 to not have two different 2.0 versions floating around. Do you agree with this?

**Comment by bizzinho** [comment]
I'll send you the combined version together with the fixed ADDICT in a couple of minutes. Could you please have a look at the other comment above?

**Comment by Jinjin-Li** [comment]
I agree with all your comment. 
We have lost touch with Seung Ha. We don't know where she is and what she is doing now.

**Comment by bizzinho** [comment]
Yes, but that is irrelevant to the question, which pertains to when she STARTED working on ADDICT and when she stopped? Certainly you know this. The copyright statement requires year information to be valid according to US law.

**Comment by Jinjin-Li** [comment]
Sorry
2012-2014 Dr. Seung Ha Kim;
2014-2016 Dr. Jinjin Li;
2016 Dr. David Ochsenbein.

**Comment by bizzinho** [comment]
Thanks a lot. Please let me know regarding the facet-order issue when you can. I'm sending you the new versions now.

**Comment by Jinjin-Li** [comment]
OK, I will let you know.
Thank you.

**Comment by Jinjin-Li** [comment]
Dave, I received the new ADDICT version. Thanks.
By the way, what do you mean "the order depends solely on the first op. Condition"?
Is this means if the first op. condition is vapor, the order depends on vapor? If the first op. condition is water, the order will depend on water?
Am I right?

**Comment by bizzinho** [comment]
Exactly, yes!

Sent from my phone.

-----Original Message-----

**Comment by bizzinho** [comment]
Hey Jinjin,

Any update on this?


Best,
Dave
