### ISSUE TITLE
The Export Figures doesn't work

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#37]
Dave, I find that the button of "Export Figures" in ADDICT v2.1 doesn't work. I tested the vapor calculations for Paracetamol and Naphthalene.
![export figures](https://cloud.githubusercontent.com/assets/17035064/14944588/8a0d641a-0fac-11e6-9f4a-00aae67e2357.png)

**Comment by bizzinho** [comment]
Jinjin,

I’m currently out of the country, I will look at it after I’m back (Sat or Sun this week).


Best,
Dave

**Comment by Jinjin-Li** [comment]
Dave, don't forget to look at this. Thank you.

**Comment by bizzinho** [comment]
Fixed
