### ISSUE TITLE
The bug for 'Load old state'

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#38]
Dave,
The "Load old state" in the update ADDICT version you sent it to me yesterday doesn't work. Could you please fix it. 
Thanks
![1](https://cloud.githubusercontent.com/assets/17035064/15130358/ae00570a-15fc-11e6-8236-b2cd82bb137f.jpg)

**Comment by bizzinho** [comment]
fixed
