### ISSUE TITLE
output figures

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#6]
I can't find the figures in the output folder. It seems like all the figures have been saved in the ADDICT file, not the output file.

**Comment by bizzinho** [comment]
Can you specificy what you mean with ADDICT file?

**Comment by Jinjin-Li** [comment]
I mean the file containing all the Matlab (*.m) files.  (The Shape file, which you sent it to us.)
Currently, the output figures are saved in the Shape file no matter which compound we calculate.
But we want to save the output figures in the output file (which contains the CIF file), when we click the "Export figures".




 
From: Dave Ochsenbein
Date: 2016-02-02 23:55
To: bizzinho/ADDICT_Issues
CC: Jinjin-Li
Subject: Re: [ADDICT_Issues] output figures (#6)
Can you specificy what you mean with ADDICT file?
―

**Comment by bizzinho** [comment]
Ahh, ok. -> Folder, not file. I was confused because the data can be stored in the ADDICT mat-file…

Will fix it

**Comment by Jinjin-Li** [comment]
Ahh, Yes. It's folder.
Sorry......

-----Original Message-----

**Comment by bizzinho** [comment]
This has been fixed in the latest version

**Comment by Jinjin-Li** [comment]
Hi Dave,
Thank you for providing the ADDICT update version. Please see the new error in attachment.

Jinjin
