### ISSUE TITLE
Slider labeling

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#9]
![slider labeling](https://cloud.githubusercontent.com/assets/16385845/12906672/8d8d158c-ce97-11e5-9588-3254a99c6bc7.PNG)

The x-axis label is partially covered by the slider (see image above).  Also, right now the slider has no labeling and cycling through the predicted shapes keeps the slider in the middle position of the bar. Does the slider represent different values when a different predicted shape is selected (upon cycling through solvent sweep results for example)?

**Comment by bizzinho** [comment]
The slider position will change with the actual ratio when cycling... naphtalene is somehow a special case in that the ratio between L3 and L4 does not seem to vary at all... However, this comes staright from ADDICT's predictions, so I cannot really do much about it :/

I have modified the height of the axis and added a label on the slider. Let me know if there is something more I can do about this.

PS. The plot looks slightly different on 2015 and 2013 Matlab... it might be that in 2013 things are still cut off, please let me know if this is the case.
